language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
script:
  - composer require codeclimate/php-test-reporter --dev
  - echo "Running PHPUnit Tests"
  - phpunit --coverage-clover build/logs/clover.xml tests/*
after_script:
  - vendor/bin/test-reporter
